### ISSUE TITLE
Installation fails inelegantly when GOPATH is not set 

### ISSUE THREAD

**Issue by geekygirldawn** [dims/maintainers#18]
While I'm not surprised that the installation script failed because my GOPATH wasn't set, I had to read the installation script to figure out why, since it wasn't clear from the error message.

Here's a reproduction of the error.
```
fosterd@fosterd-a02 maintainers % make
./hack/install-maintainers.sh
go build github.com/dims/maintainers: copying /var/folders/xt/0sbwl11j167fjmjjpxjrs5fc0000gp/T/go-build3664102535/b001/exe/a.out: open /bin/maintainers: operation not permitted
make: *** [install] Error 1
fosterd@fosterd-a02 maintainers % echo $GOPATH

fosterd@fosterd-a02 maintainers % export GOPATH=$HOME/go
fosterd@fosterd-a02 maintainers % make
./hack/install-maintainers.sh
maintainers installed to /Users/fosterd/go/bin
```

**Comment by geekygirldawn** [comment]
I'm also curious why this is building from github.com/dims/maintainers, instead of kubernetes-sigs?

**Comment by dims** [comment]
cc @MadhavJivrajani

**Comment by nikhita** [comment]
> I'm also curious why this is building from github.com/dims/maintainers, instead of kubernetes-sigs?

module name and paths need to be updated - https://github.com/kubernetes-sigs/maintainers/blob/main/go.mod#L1

/assign @RaghavRoy145

**Comment by MadhavJivrajani** [comment]
Closing on account of https://github.com/kubernetes-sigs/maintainers/pull/23 being merged!
